chat/urls.py
"""
Chat URL Configuration
"""

from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.utils.translation import gettext_lazy as _

from .views import (
    about_page,
    log_in,
    log_out,
    sign_up,
    user_list,
    user_map,
    ThreadView,
    call_view,
    ProfileView,
)


app_name = "Chat"

urlpatterns = [
    path("about", about_page, name="about_page"),
    path("login", log_in, name="login"),
    path("logout", log_out, name="logout"),
    path("signup", sign_up, name="signup"),
    path("", user_list, name="user_list"),
    path("users", user_map, name="users_map"),
    path("user/<str:username>", ProfileView.as_view(), name="user"),
    path("chat/<str:username>", ThreadView.as_view(), name="chat"),
    path("thread/<int:thread_id>", ThreadView.as_view(), name="thread"),
    path("call/<str:username>", call_view, name="call"),
]
admin.site.site_header = _("Chat administration")

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "About us" %}{% endblock title %}
{% block description %}{% trans 'Simple chat site with a chatbot' %}{% endblock description %}

{% block content %}
    <div class="container">
        <div class="jumbotron mt-5">
            <h1 class="mb-4"><wbr>{% trans "About us" %}</h1>
            <p>{% trans "Simple chat site with a chatbot." %}</p>
            <p>{% trans "Link to the repository:" %} <a href="https://bitbucket.org/voron-raven/chat">https://bitbucket.org/voron-raven/chat</a></p>
            <p>{% trans "Site owner:" %} <a href="https://www.linkedin.com/in/mykhailokeda/">Mykhailo Keda</a></p>
        </div>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QMOFBUIlPIK7gAAAdxJREFUWMPll8FqFEEQhr/+K6IxqAgBEQ+LoiCKkJMH8RFE8RkEjyJ4M3mBHHwYjSdvQkAQYS+LohcTDWpQoyjioukqDzuDu8asG9nZPqSgT1PM93dVd1cV7HZLozqa7DRwBbgInAVagKrPAbwGOsByEEvu3hmLQpPdNtkHk8UO14bJ5tHomwRAUg2++R/Q7dat6p/DU2DJSCkdDOIRcGbM6X4OnCfxJee8VYCZQdCqHPc2dOZ+AqdIrNYiUh0ad5+V9AbY0/DBz+5+RNLH7Ll3irNnJD2ZALy3X6mdvRcBqyKwAFyd4PU/lFKKiHhYpyBKPELZczKTXQMulxCgpLcqBa/skoC5ggLmksm6Dd77f9mm6ptQyLKAdwUFrAtoFxTQFrBUUMC94g9R3dEsFODPD5Zj2UrVZk3CXmbPJwbKMXAYWJ9ARfwBHCXYyNFXjkl8cvw40G0Q3nX8JKkH39KSKQmZ9oXH9wbgnUS64OFfPfw3s99j2qYJjyaK043s+ZwzCP/rXGCyNeDYGKDvgTvZ8+Iwp6k/4NdHgN+vOuZWXx3ZBFaAp8AycDd7frGjWcBkB4b09d9Mtmiy/ePOzRSAu2OyepT6DLwCngXxmOCBx5jGrO1sRjO7dzr+BVtAwsorwcB8AAAAAElFTkSuQmCC" rel="icon"/>
  <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}?v=3"/>
  {% block css %}{% endblock css %}
  <title>{% block title %}{% trans "Chat room" %}{% endblock title %}</title>
  <meta name="description" content="{% block description %}{% trans 'Chat with users or chatbot' %}{% endblock description %}"/>
</head>
<body>
<svg class="hidden-xl-down">
  <defs>
    <symbol id="chat-icon" viewBox="0 0 14 14">
      <path d="M7,0.935c-3.866,0-7,2.463-7,5.5c0,1.438,0.703,2.749,1.854,3.729   c-0.044,0.955-0.242,2.239-0.942,2.901c1.337,0,2.706-0.88,3.518-1.514c0.796,0.248,1.663,0.384,2.57,0.384c3.866,0,7-2.463,7-5.5   S10.866,0.935,7,0.935z" fill="#006DF0"/>
    </symbol>
  </defs>
</svg>
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'core:user_list' %}">{% trans "Chat" %}</a>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        {% with '/chat/chatbot' as chatbot_url %}
        <li class="nav-item {% if request.get_full_path == chatbot_url %}active{% endif %}">
          <a class="nav-link" href="{{ chatbot_url }}">{% trans "Chatbot" %}</a>
        </li>
        {% endwith %}
        {% with '/chat/ChatGPT' as chat_gpt_url %}
        <li class="nav-item {% if request.get_full_path == chat_gpt_url %}active{% endif %}">
          <a class="nav-link" href="{{ chat_gpt_url }}">ChatGPT</a>
        </li>
        {% endwith %}
        {% endif %}
        {% if user.is_staff %}
        {% url 'core:users_map' as users_url %}
        <li class="nav-item {% if request.get_full_path == users_url %}active{% endif %}">
          <a class="nav-link" href="{{ users_url }}">{% trans "Users" %}</a>
        </li>
        {% endif %}
        {% url 'core:about_page' as about_url %}
        <li class="nav-item {% if request.get_full_path == about_url %}active{% endif %}">
          <a class="nav-link" href="{{ about_url }}">{% trans "About" %}</a>
        </li>
      </ul>
      <ul class="navbar-nav mr-right">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg class="icon">
              <use xlink:href="#chat-icon" />
            </svg>
             {% if unread_threads %}<span class="badge badge-pill badge-danger">{{ unread_threads }}</span>{% endif %}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            {% for thread in threads %}
            <a class="dropdown-item" href="{% url 'core:thread' thread.id %}">{{ thread.name }}</a>
            {% endfor %}
          </div>
        </li>
        {% url 'core:user' user.username as user_url %}
        <li class="nav-item {% if request.get_full_path == user_url %}active{% endif %}">
          <a class="nav-link" href="{{ user_url }}">
            <img src="{{ user.profile.avatar.url }}" height="20" width="20" alt="avatar">
            {{ user.username }}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:logout' %}">{% trans "Log out" %}</a>
        </li>
        {% else %}
        {% url 'core:signup' as signup_url %}
        <li class="nav-item {% if request.path == signup_url %}active{% endif %}">
          <a class="nav-link" href="{{ signup_url }}">{% trans "Sign up" %}</a>
        </li>
        {% url 'core:login' as login_url %}
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ login_url }}">{% trans "Log in" %}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% block content %}{% endblock content %}

  <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'bower_components/tether/dist/js/tether.min.js' %}"></script>
  <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bower_components/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js' %}"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-74402136-5', 'auto');
    ga('send', 'pageview');
  </script>
  {% block script %}{% endblock script %}
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Login" %}{% endblock title %}
{% block description %}{% trans 'Login to chat with users and chatbot' %}{% endblock description %}

{% block content %}
<div class="container">
  <div class="jumbotron mt-5">
  <form action="{% url 'core:login' %}" method="post" class="">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
        </div>
      </div>
    {% endfor %}
    {% if form.non_field_errors %}
      <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
        {{ form.non_field_errors }}
      </div>
    {% endif %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Log in" %}</button>
  </form>


  <a href="{% url 'social:begin' 'facebook' %}">{% trans "Login with Facebook" %}</a>
  <p>{% trans "Don't have an account?" %} <a href="{% url 'core:signup' %}">{% trans "Sign up!" %}</a></p>
  </div>
</div>
{% endblock content %}

templates/message.html
{% url 'core:user' message.user.username as user_url %}
<li id="message-{{ message.pk }}" lang="{{ message.lang }}" class="{% if user.pk == message.user.pk %}right{% else %}left{% endif %} clearfix message {% if not message %}hidden-xs-up{% endif %}">
    <span class="chat-img">
        <a href="{{ user_url }}">
            <img src="{{ message.avatar }}" width="50" height="50" alt="User Avatar" class="avatar" />
        </a>
    </span>
    <div class="chat-body clearfix">
        <div class="header">
            <a href="{{ user_url }}" class="text-muted profile-link">
                <strong class="username primary-font">{{ message.user.username }}</strong>
            </a>
            <small class="text-muted date-wrapper"><time class="date" datetime="{{ message.date }}">{{ message.date|timesince }}</time> ago</small>
        </div>
        <p class="text">{{ message.text }}</p>
    </div>
</li>

templates/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Profile" %}{% endblock title %}

{% block content %}
<div class="container">
    <div class="jumbotron bg-white mt-5">
        <div class="row my-2">
            <div class="col-lg-8 push-lg-4">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">{% trans "Profile" %}</a>
                    </li>
                    <li class="nav-item">
                        {% if is_editing_allowed %}
                            <a href="" data-target="#chats" data-toggle="tab" class="nav-link">{% trans "Chats" %}</a>
                        {% else %}
                            <a href="{% url 'core:chat' profile_user.username %}" class="name nav-link text-muted">{% trans "Chat" %}</a>
                        {% endif %}
                    </li>
                </ul>
                <div class="tab-content p-b-3">
                    <div class="tab-pane active" id="profile">
                        <h4 class="my-2">{% trans "User Profile" %}</h4>
                        <div class="row">
                            <div class="col-md-12 mt-3">
                                <div class="form-group row">
                                    <div class="col-md-4 float-left"><h6>{% trans "First name" %}</h6></div>
                                    <div class="col-md-8 float-right">
                                        {% if is_editing_allowed %}
                                            <a href="#" id="first_name" class="editable" data-type="text" data-pk="first_name" data-url="{% url 'core:user' profile_user.username %}" data-placeholder="{% trans 'Enter first name' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.first_name }}</a>
                                        {% else %}
                                            {{ profile_user.first_name }}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4 float-left"><h6>{% trans "Last name" %}</h6></div>
                                    <div class="col-md-8 float-right">
                                        {% if is_editing_allowed %}
                                            <a href="#" id="last_name" class="editable" data-type="text" data-pk="last_name" data-url="{% url 'core:user' profile_user.username %}" data-placeholder="{% trans 'Enter last name' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.last_name }}</a>
                                        {% else %}
                                            {{ profile_user.last_name }}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4 float-left"><h6>{% trans "Email" %}</h6></div>
                                    <div class="col-md-8 float-right">
                                        {% if is_editing_allowed %}
                                            <a href="#" id="email" class="editable" data-type="email" data-pk="email" data-url="{% url 'core:user' profile_user.username %}" data-placeholder="{% trans 'Enter email' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.email }}</a>
                                        {% else %}
                                            {{ profile_user.email }}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/row-->
                    </div>
                    {% if is_editing_allowed %}
                    <div class="tab-pane" id="chats">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>{% trans "Chat" %}</th>
                                    <th class="text-right">{% trans "Last message" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for thread in profile_threads %}
                                <tr>
                                    <td>
                                        <a href="{% url 'core:thread' thread.id %}" class="name text-muted">{{ thread.name }}</a>
                                    </td>
                                    <td class="text-right">
                                        <small>{{ thread.last_message|date:"H:i d M Y" }}</small>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4 pull-lg-8 text-center">
                <img src="{{ profile_user.profile.avatar.url }}" class="m-x-auto img-fluid rounded-circle" alt="avatar">
                {% if is_editing_allowed %}
                    <h6 class="mt-2">{% trans "Upload a different photo" %}</h6>
                    <form action="{% url 'core:user' profile_user.username %}" method="post" enctype="multipart/form-data" id="avatar-upload">
                        {% csrf_token %}
                            {% for field in form %}
                                <label class="custom-file text-left" for="{{ field.auto_id }}">
                                    {{ field|add_class:"custom-file-input" }}
                                    <span class="custom-file-control"></span>
                                </label>
                            {% if field.errors %}
                                <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
  <script>
      // Set up and initialize editable.
      $.fn.editable.defaults.mode = 'inline';
      $('.editable').editable();

      $('#avatar-upload').change(function() {
          $(this).submit();
      });
  </script>
{% endblock script %}

templates/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Sign up" %}{% endblock title %}
{% block description %}{% trans 'Sign up to chat with users or chatbot' %}{% endblock description %}

{% block content %}
<div class="container">
  <div class="jumbotron mt-5">
  <form action="{% url 'core:signup' %}" method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
      {{ form.non_field_errors }}
    </div>
    {% endif %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        </div>
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Sign up" %}</button>
    <p>{% trans "Already have an account?" %} <a href="{% url 'core:login' %}">{% trans "Log in!" %}</a></p>
  </form>
  </div>
</div>
{% endblock content %}

templates/thread.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ thread.name }}{% endblock title %}

{% block content %}
<div class="jumbotron thread-jumbotron bg-white">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                <div class="panel panel-primary">
                    <div class="panel-heading clearfix">
                        <h4 class="clearfix">
                            <a href="#" id="name" class="editable" data-type="text" data-pk="name" data-url="{% url 'core:thread' thread.pk %}" data-placeholder="{% trans 'Enter thread title' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ thread.name }}</a>
                            {% if interlocutor %}
                                <a href="{% url 'core:call' interlocutor.username %}" class="h2 float-right">☎</a>
                            {% endif %}
                        </h4>
                    </div>
                    <div id="chat-body" class="panel-body bg-faded p-2">
                        <ul id="messages" class="chat">
                            {% include "message.html" %}
                            {% for message in messages %}
                                {% include "message.html" %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="panel-footer">
                        <div class="input-group">
                            <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                            <span class="input-group-btn">
                                <button class="btn btn-warning btn-sm" id="btn-chat">
                                    Send</button>
                            </span>
                        </div>
                        <label class="h6" for="read-messages">
                            <input type="checkbox" id="read-messages" value="" checked> {% trans "Read messages" %}
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
  <script>
    var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    var socket = new WebSocket(protocol + '://' + window.location.host + '/ws/thread/' + {{ thread.id }});
    var users = {% autoescape off %}{{ users }}{% endautoescape %};
    var user = {{ user.pk }};
    var $input = $('#btn-input');
    var $chat = $('#chat-body');
    var read_messages = document.getElementById('read-messages');
    var $message;
    var msg;

    function sendMessage() {
      socket.send(JSON.stringify({
        text: $input.val()
      }));
      $input.val('');
    }

    // Set up and initialize editable.
    $.fn.editable.defaults.mode = 'inline';
    $('.editable').editable();

    $chat.scrollTop($chat.prop('scrollHeight'));

    $('#btn-chat').click(sendMessage);
    $input.keypress(function(e) {
      if (e.which === 13) {
        sendMessage();
      }
    });

    socket.onmessage = function message(event) {
      var raw_data = JSON.parse(event.data);
      var action = raw_data.payload.action;
      var data = raw_data.payload.data.fields;
      var pk = raw_data.payload.pk;

      // On message Update.
      if (action === 'update') {
        $message = $('#message-' + pk);
        $message.find('.text').text(data.text);
      }

      // On message Insert.
      if (action === 'create') {
        $message = $('#message-').clone().toggleClass('left', data.user !== user).toggleClass('right', data.user === user).removeClass('hidden-xs-up').attr('id', 'message-' + pk).appendTo('#messages');
        $message.attr('lang', data.lang);
        $message.find('.text').text(data.text);
        $message.find('.date').data('date', data.date).text('{% trans "Just now" %}');
        if (users.hasOwnProperty(data.user)) {
          // TODO [Mike] Need to think how to improve this.
          $message.find('.profile-link').attr('href', '/user/' + users[data.user].username);
          $message.find('.username').text(users[data.user].username);
          $message.find('.avatar').attr('src', users[data.user].avatar);
        }

        // Confirm that message was read.
        socket.send(JSON.stringify({
          read: true
        }));

        if (read_messages.checked) {
          msg = new SpeechSynthesisUtterance(data.text);

          // Try to use preferenced voice.
          msg.voice = window.speechSynthesis.getVoices().filter(function(voice) {
            if (data.lang === 'en') {
              return voice.name === 'Google UK English Male';
            }
            if (data.lang === 'es') {
              return voice.name === 'Google español';
            }
            if (data.lang === 'fr') {
              return voice.name === 'Google français';
            }
          })[0];

          // Set at last lang.
          if (msg.voice == null) {
            msg.lang = data.lang;
          }
          window.speechSynthesis.cancel();
          window.speechSynthesis.speak(msg);
        }
      }

      // On message Delete.
      if (action === 'delete') {
        $('#message-'+pk).remove();
      }
      $chat.scrollTop($chat.prop('scrollHeight'));
    };
  </script>
{% endblock script %}

templates/user_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock title %}
{% block description %}{% trans 'List of users with their statuses and last login date' %}{% endblock description %}

{% block content %}
<div class="container">
    <div class="jumbotron bg-white mt-5">

        <ul class="list-group users-list">
            {% for user in users %}
                <li data-username="{{ user.username }}" class="list-group-item justify-content-between">
                    <a href="{% url 'core:chat' user.username %}" class="name text-muted">{{ user.username }}</a>
                    <div>
                        <small class="text-muted">{{ user.last_login|date:"d/m/Y" }}</small>
                        <span class="status badge badge-default badge-pill">
                            <a href="{% url 'core:user' user.username %}" class="text-white">
                                {% trans "Offline" %}
                            </a>
                        </span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

{% block script %}
  <script>
    var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    var socket = new WebSocket(protocol + '://' + window.location.host + '/ws/users/');
    var $users_list = $('.users-list');
    var $user;
    var data;

    socket.onmessage = function message(event) {
      data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      if (Array.isArray(data)) {
        // Set Offline for all users.
        $users_list.find('li .status').removeClass('badge-success').find('a').text('Offline');
      }
      jQuery.each(data, function(username, is_logged_in) {
        if (typeof(username) === 'number') {
          // It's a list of online users.
          username = is_logged_in;
          is_logged_in = true;
        }
        $user = $users_list.find('li').filter(function () {
          return $(this).data('username') === username;
        });

        $user.find('.name').text(username);
        if (is_logged_in) {
          $user.find('.status').addClass('badge-success').find('a').text('Online');
        }
        else {
          $user.find('.status').removeClass('badge-success').find('a').text('Offline');
        }
      });
    };
  </script>
{% endblock script %}

templates/users_map.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock title %}
{% block description %}{% trans 'Map of users' %}{% endblock description %}

{% block content %}
<div style="margin-top: 56px; width: 100%; height: calc(100vh - 56px);">
    <div id="map" style="height: 100%;"></div>
    <script>
      function initMap() {
        var data = {{ users|safe }};
        var marker;
        var cluster_markers;
        var titles;
        var info;
        var i;
        var infowindow = new google.maps.InfoWindow();
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 2,
          maxZoom: 7,
          center: {lat: 28.024, lng: 40.887}
        });
        var markers = data.map(function(user) {
          marker = new google.maps.Marker({
            position: user.location,
            label: user.username
          });

          google.maps.event.addListener(marker, 'click', (function () {
              return function () {
                  window.location = user.profile;
              };
          })(marker));

          return marker;
        });

        // Add a marker clusterer to manage the markers.
        var markerCluster = new MarkerClusterer(map, markers, {
          imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'
        });

        google.maps.event.addListener(markerCluster, 'clusterclick', function(cluster) {
          info = new google.maps.MVCObject;
          info.set('position', cluster.center_);

          cluster_markers = cluster.getMarkers();

          titles = "";
          for (i = 0; i < cluster_markers.length; i++) {
            titles += "<a href='/user/" + cluster_markers[i].label + "'>" + cluster_markers[i].label + "</a>, ";
          }
          titles = titles.slice(0, -2);

          infowindow.close();
          infowindow.setContent(titles);
          infowindow.open(map, info);
        });
      }
    </script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_map_api_key }}&callback=initMap"></script>
</div>
{% endblock content %}